export const typeCardsInfo = [
  {
    id: 1,
    img: "https://i.ibb.co/QKz7p46/multi-Family.png",
    alt: "multi Family",
    title: "Багатосімейні",
    description:
      "Широкий спектр варіантів для вашої сім'ї та особистого простору.",
    linkTo: "?prop_type=multi",
  },
  {
    id: 2,
    img: "https://i.ibb.co/qNXHmkF/town-Houses.png",
    alt: "town Houses",
    title: "Міські",
    description: "Різні можливості для комфортного міського життя.",
    linkTo: "?prop_type=urban",
  },
  {
    id: 3,
    img: "https://i.ibb.co/S6dHMPW/condos.png",
    alt: "condos",
    title: "Кондомініуми",
    description: "Сучасні рішення для вашого дому із забезпеченням зручностей.",
    linkTo: "?prop_type=condos",
  },
  {
    id: 4,
    img: "https://i.ibb.co/KzgZfyf/duplex.png",
    alt: "duplex",
    title: "Дуплекси",
    description: "Ідеальні варіанти для тих, хто шукає простір і приватність.",
    linkTo: "?prop_type=multi",
  },
  {
    id: 5,
    img: "https://i.ibb.co/jLFVpJg/single-Family.png",
    alt: "single Family",
    title: "Односімейні",
    description: "Привабливі домівки для індивідуального проживання.",
    linkTo: "?prop_type=single",
  },
  {
    id: 6,
    img: "https://i.ibb.co/xzqkH27/mobile.png",
    alt: "mobile",
    title: "Мобільні",
    description: "Гнучкі рішення для життя на колесах з усіма зручностями.",
    linkTo: "?prop_type=mobile",
  },
];
